"""autogen

Revision ID: 04832691e35f
Revises: 0001_init
Create Date: 2026-02-11 04:04:51.576591
"""

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '04832691e35f'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_metadata', sa.Column('start_date_source_doc_id', sa.UUID(), nullable=True))
    op.add_column('case_metadata', sa.Column('start_date_page', sa.Integer(), nullable=True))
    op.add_column('case_metadata', sa.Column('start_date_bbox', sa.JSON(), nullable=True))
    op.add_column('case_metadata', sa.Column('end_date_source_doc_id', sa.UUID(), nullable=True))
    op.add_column('case_metadata', sa.Column('end_date_page', sa.Integer(), nullable=True))
    op.add_column('case_metadata', sa.Column('end_date_bbox', sa.JSON(), nullable=True))
    op.add_column('case_metadata', sa.Column('daily_salary_source_doc_id', sa.UUID(), nullable=True))
    op.add_column('case_metadata', sa.Column('daily_salary_page', sa.Integer(), nullable=True))
    op.add_column('case_metadata', sa.Column('daily_salary_bbox', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'case_metadata', 'documents', ['end_date_source_doc_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'case_metadata', 'documents', ['daily_salary_source_doc_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'case_metadata', 'documents', ['start_date_source_doc_id'], ['id'], ondelete='SET NULL')
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=Vector(dim=384),
        type_=Vector(dim=1024),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=Vector(dim=1024),
        type_=Vector(dim=384),
        existing_nullable=True,
    )
    op.drop_constraint(None, 'case_metadata', type_='foreignkey')
    op.drop_constraint(None, 'case_metadata', type_='foreignkey')
    op.drop_constraint(None, 'case_metadata', type_='foreignkey')
    op.drop_column('case_metadata', 'daily_salary_bbox')
    op.drop_column('case_metadata', 'daily_salary_page')
    op.drop_column('case_metadata', 'daily_salary_source_doc_id')
    op.drop_column('case_metadata', 'end_date_bbox')
    op.drop_column('case_metadata', 'end_date_page')
    op.drop_column('case_metadata', 'end_date_source_doc_id')
    op.drop_column('case_metadata', 'start_date_bbox')
    op.drop_column('case_metadata', 'start_date_page')
    op.drop_column('case_metadata', 'start_date_source_doc_id')
    # ### end Alembic commands ###
